name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.15.0" # specify your Node.js version

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0 # specify your desired PNPM version

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build the site
        run: pnpm build

      - name: Upload your site
        uses: withastro/action@v2
        with:
          path: . # The root location of your Astro project inside the repository. (optional)
          # node-version: 20  # This is already specified in the setup-node step above.
          package-manager: pnpm # Specify that PNPM should be used

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
